//===----------------------------------------------------------------------===//
// Copyright (c) 2026 ReticulumSwift contributors.
//
// Licensed under the Reticulum License. See LICENSE in the repository root for
// the full license text, and NOTICE for attribution of the upstream project
// this file is derived from.
//
// SPDX-License-Identifier: LicenseRef-Reticulum
//===----------------------------------------------------------------------===//

import XCTest

@testable import ReticulumSwift

/// Every command line recorded from the reference, and what it came to.
final class RNGitCommandLineVectorTests: XCTestCase {

  /// What one recorded `rngit` command line came to.
  private struct Run {
    let name: String
    let arguments: [String]
    let standardOutput: String
    let standardError: String
    let exitCode: Int32?
    let setup: Setup?
  }

  /// What one recorded run brings up.
  private struct Setup {
    let configDirectory: String?
    let rnsConfigDirectory: String?
    let verbosity: Int
    let quietness: Int
    let service: Bool?
    let interactive: Bool?
    let printIdentity: Bool?
    let identity: String?
    let signer: String?
    let task: Task?
  }

  /// What one recorded run was asked to do.
  private struct Task {
    let command: String
    let operation: String?
    let remote: String?
    let source: String?
    let target: String?
    let signer: String?
    let name: String?
    let noUpload: Bool?
    let offline: Bool?
    let scope: String?
    let documentIdentifier: Int?
    let title: String?
  }

  /// What one recorded `git-remote-rns` command line came to.
  private struct Reading {
    let name: String
    let arguments: [String]
    let environment: [String: String]
    let standardError: String
    let exitCode: Int32?
    let configDirectory: String?
    let rnsConfigDirectory: String?
    let destination: String?
    let group: String?
    let repository: String?
  }

  /// Every `rngit` command line recorded from the reference.
  private static let runs: [Run] = [
    Run(
      name: "no arguments",
      arguments: [],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: false,
        interactive: false,
        printIdentity: false,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node named",
      arguments: ["node"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: false,
        interactive: false,
        printIdentity: false,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node with a config directory",
      arguments: ["node", "--config", "/tmp/one"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: "/tmp/one",
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: false,
        interactive: false,
        printIdentity: false,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node with a reticulum config directory",
      arguments: ["node", "--rnsconfig", "/tmp/two"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: "/tmp/two",
        verbosity: 0,
        quietness: 0,
        service: false,
        interactive: false,
        printIdentity: false,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node printing its identity",
      arguments: ["node", "-p"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: false,
        interactive: false,
        printIdentity: true,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node printing its identity spelled out",
      arguments: ["node", "--print-identity"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: false,
        interactive: false,
        printIdentity: true,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node as a service",
      arguments: ["node", "-s"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: true,
        interactive: false,
        printIdentity: false,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node interactive",
      arguments: ["node", "-i"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: false,
        interactive: true,
        printIdentity: false,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node verbose",
      arguments: ["node", "-v"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 1,
        quietness: 0,
        service: false,
        interactive: false,
        printIdentity: false,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node verbose three times",
      arguments: ["node", "-vvv"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 3,
        quietness: 0,
        service: false,
        interactive: false,
        printIdentity: false,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node quiet",
      arguments: ["node", "-q"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 1,
        service: false,
        interactive: false,
        printIdentity: false,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node verbose and quiet",
      arguments: ["node", "-vv", "-q"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 2,
        quietness: 1,
        service: false,
        interactive: false,
        printIdentity: false,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "node with every flag",
      arguments: ["node", "-p", "-s", "-i", "-vv"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 2,
        quietness: 0,
        service: true,
        interactive: true,
        printIdentity: true,
        identity: nil,
        signer: nil,
        task: nil)),
    Run(
      name: "a word that names no subcommand",
      arguments: ["nonesuch"],
      standardOutput: "",
      standardError:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-p] [-s] [-i]\n             [-v] [-q] [--version]\nrngit: error: unrecognized arguments: nonesuch\n",
      exitCode: 2,
      setup: nil),
    Run(
      name: "create",
      arguments: ["create", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "create",
          operation: "create",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "create with an identity",
      arguments: ["create", "-i", "/tmp/id", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: "/tmp/id",
        signer: nil,
        task: Task(
          command: "create",
          operation: "create",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "create with an identity spelled out",
      arguments: [
        "create", "--identity", "/tmp/id", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: "/tmp/id",
        signer: nil,
        task: Task(
          command: "create",
          operation: "create",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "create without a repository",
      arguments: ["create"],
      standardOutput: "",
      standardError:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH] [-v]\n             [-q] [--version]\n             repository\nrngit: error: the following arguments are required: repository\n",
      exitCode: 2,
      setup: nil),
    Run(
      name: "release listing",
      arguments: ["release", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "list"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: "list",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release viewing",
      arguments: ["release", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "view", "v1.0"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: "view",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: "v1.0",
          signer: nil,
          name: nil,
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release fetching",
      arguments: ["release", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "fetch", "v1.0"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: "fetch",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: "v1.0",
          signer: nil,
          name: nil,
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release verifying",
      arguments: [
        "release", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "verify", "v1.0",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: "verify",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: "v1.0",
          signer: nil,
          name: nil,
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release creating",
      arguments: [
        "release", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "create", "v1.0",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: "create",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: "v1.0",
          signer: nil,
          name: nil,
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release creating locally",
      arguments: [
        "release", "-L", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "create", "v1.0",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: "create",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: "v1.0",
          signer: nil,
          name: nil,
          noUpload: true,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release creating with a name",
      arguments: [
        "release", "-n", "pkg", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "create",
        "v1.0",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: "create",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: "v1.0",
          signer: nil,
          name: "pkg",
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release creating with a signer",
      arguments: [
        "release", "-s", "/tmp/sig", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "create",
        "v1.0",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: "/tmp/sig",
        task: Task(
          command: "release",
          operation: "create",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: "v1.0",
          signer: "/tmp/sig",
          name: nil,
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release fetching offline",
      arguments: [
        "release", "-o", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "fetch", "v1.0",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: "fetch",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: "v1.0",
          signer: nil,
          name: nil,
          noUpload: false,
          offline: true,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release latest",
      arguments: ["release", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "latest"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: "latest",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release deleting",
      arguments: [
        "release", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "delete", "v1.0",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: "delete",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: "v1.0",
          signer: nil,
          name: nil,
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release without an operation",
      arguments: ["release", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH]\n             [-s PATH] [-n name] [-L] [-o] [-v] [-q] [--version]\n             [repository] [operation] [target]\n\nReticulum Git Release Manager\n\npositional arguments:\n  repository            URL of remote repository, or path to RSM manifest\n  operation             list, view, fetch, verify, create, latest or delete\n  target                tag and path to release artifacts directory\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to release identity\n  -s PATH, --signer PATH\n                        path to signing identity, if different from release\n                        identity\n  -n name, --name name  package name if different from repo name\n  -L, --local           generate release locally, but don't upload\n  -o, --offline         verify manifest locally, but don't fetch updates\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: nil,
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "release bare",
      arguments: ["release"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH]\n             [-s PATH] [-n name] [-L] [-o] [-v] [-q] [--version]\n             [repository] [operation] [target]\n\nReticulum Git Release Manager\n\npositional arguments:\n  repository            URL of remote repository, or path to RSM manifest\n  operation             list, view, fetch, verify, create, latest or delete\n  target                tag and path to release artifacts directory\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to release identity\n  -s PATH, --signer PATH\n                        path to signing identity, if different from release\n                        identity\n  -n name, --name name  package name if different from repo name\n  -L, --local           generate release locally, but don't upload\n  -o, --offline         verify manifest locally, but don't fetch updates\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "release",
          operation: nil,
          remote: nil,
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: false,
          offline: false,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "permissions on a repository",
      arguments: ["perms", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "perms",
          operation: "rperms",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "permissions on a group",
      arguments: ["perms", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "perms",
          operation: "gperms",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "permissions on a repository with a trailing slash",
      arguments: ["perms", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo/"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "perms",
          operation: "rperms",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "permissions on a group with a trailing slash",
      arguments: ["perms", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "perms",
          operation: "gperms",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "permissions on a URL naming too little",
      arguments: ["perms", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH] [-v]\n             [-q] [--version]\n             remote\n\nReticulum Git Release Manager\n\npositional arguments:\n  remote                URL of remote group or repository\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to release identity\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n\nInvalid URL\n",
      standardError: "",
      exitCode: 1,
      setup: nil),
    Run(
      name: "permissions on a URL naming too much",
      arguments: ["perms", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo/more"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH] [-v]\n             [-q] [--version]\n             remote\n\nReticulum Git Release Manager\n\npositional arguments:\n  remote                URL of remote group or repository\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to release identity\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n\nInvalid URL\n",
      standardError: "",
      exitCode: 1,
      setup: nil),
    Run(
      name: "work listing",
      arguments: ["work", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "list"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "list",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "work listing completed",
      arguments: [
        "work", "--scope", "completed", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "list",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "list",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "completed",
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "work viewing",
      arguments: ["work", "-d", "7", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "view"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "view",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: 7,
          title: nil))),
    Run(
      name: "work creating with a title",
      arguments: [
        "work", "-t", "A title", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "create",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "create",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: nil,
          title: "A title"))),
    Run(
      name: "work creating with a title spelled out",
      arguments: [
        "work", "--title", "A title", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "create",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "create",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: nil,
          title: "A title"))),
    Run(
      name: "work proposing",
      arguments: ["work", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "propose"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "propose",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "work editing",
      arguments: ["work", "-d", "3", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "edit"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "edit",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: 3,
          title: nil))),
    Run(
      name: "work deleting",
      arguments: [
        "work", "-d", "3", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "delete",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "delete",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: 3,
          title: nil))),
    Run(
      name: "work updating",
      arguments: [
        "work", "-d", "3", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "update",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "update",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: 3,
          title: nil))),
    Run(
      name: "work completing",
      arguments: [
        "work", "-d", "3", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "complete",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "complete",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: 3,
          title: nil))),
    Run(
      name: "work activating",
      arguments: [
        "work", "-d", "3", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "activate",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "activate",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: 3,
          title: nil))),
    Run(
      name: "work permissions",
      arguments: ["work", "-d", "3", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "perms"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: "perms",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: 3,
          title: nil))),
    Run(
      name: "work without an operation",
      arguments: ["work", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH]\n             [--scope SCOPE] [-t TITLE] [-d ID] [-v] [-q] [--version]\n             [repository] [operation]\n\nReticulum Git Work Document Manager\n\npositional arguments:\n  repository            URL of remote repository\n  operation             list, view, create, propose, edit, delete, update,\n                        complete, activate or perms\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to identity\n  --scope SCOPE         document scope: active, completed or all\n  -t TITLE, --title TITLE\n                        document title for create\n  -d ID, --id ID        document ID\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n\n",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "work",
          operation: nil,
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: "active",
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "work with an identifier that is no number",
      arguments: ["work", "-d", "x", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "view"],
      standardOutput: "",
      standardError:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH]\n             [--scope SCOPE] [-t TITLE] [-d ID] [-v] [-q] [--version]\n             [repository] [operation]\nrngit: error: argument -d/--id: invalid int value: 'x'\n",
      exitCode: 2,
      setup: nil),
    Run(
      name: "fork",
      arguments: [
        "fork", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
        "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/mine/repo",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "fork",
          operation: "fork",
          remote: nil,
          source: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          target: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/mine/repo",
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "fork without a target",
      arguments: ["fork", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      standardOutput: "",
      standardError:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH] [-v]\n             [-q] [--version]\n             source target\nrngit: error: the following arguments are required: target\n",
      exitCode: 2,
      setup: nil),
    Run(
      name: "fork without a source or a target",
      arguments: ["fork"],
      standardOutput: "",
      standardError:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH] [-v]\n             [-q] [--version]\n             source target\nrngit: error: the following arguments are required: source, target\n",
      exitCode: 2,
      setup: nil),
    Run(
      name: "sync",
      arguments: ["sync", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "sync",
          operation: "sync",
          remote: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          source: nil,
          target: nil,
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "sync without a repository",
      arguments: ["sync"],
      standardOutput: "",
      standardError:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH] [-v]\n             [-q] [--version]\n             repository\nrngit: error: the following arguments are required: repository\n",
      exitCode: 2,
      setup: nil),
    Run(
      name: "mirror",
      arguments: [
        "mirror", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
        "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/mine/repo",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "mirror",
          operation: "fork",
          remote: nil,
          source: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          target: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/mine/repo",
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "mirror with a scope",
      arguments: [
        "mirror", "--scope", "all", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
        "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/mine/repo",
      ],
      standardOutput: "",
      standardError: "",
      exitCode: nil,
      setup: Setup(
        configDirectory: nil,
        rnsConfigDirectory: nil,
        verbosity: 0,
        quietness: 0,
        service: nil,
        interactive: nil,
        printIdentity: nil,
        identity: nil,
        signer: nil,
        task: Task(
          command: "mirror",
          operation: "fork",
          remote: nil,
          source: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo",
          target: "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/mine/repo",
          signer: nil,
          name: nil,
          noUpload: nil,
          offline: nil,
          scope: nil,
          documentIdentifier: nil,
          title: nil))),
    Run(
      name: "mirror without a source or a target",
      arguments: ["mirror"],
      standardOutput: "",
      standardError:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH]\n             [--scope SCOPE] [-v] [-q] [--version]\n             source target\nrngit: error: the following arguments are required: source, target\n",
      exitCode: 2,
      setup: nil),
    Run(
      name: "node help",
      arguments: ["node", "--help"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-p] [-s] [-i]\n             [-v] [-q] [--version]\n\nReticulum Git Repository Node\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -p, --print-identity  print identity and destination info and exit\n  -s, --service         rngit is running as a service and should log to file\n  -i, --interactive     drop into interactive shell after initialisation\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
    Run(
      name: "create help",
      arguments: ["create", "--help"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH] [-v]\n             [-q] [--version]\n             repository\n\nReticulum Git Repository Creation\n\npositional arguments:\n  repository            URL of repository to create\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to identity\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
    Run(
      name: "release help",
      arguments: ["release", "--help"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH]\n             [-s PATH] [-n name] [-L] [-o] [-v] [-q] [--version]\n             [repository] [operation] [target]\n\nReticulum Git Release Manager\n\npositional arguments:\n  repository            URL of remote repository, or path to RSM manifest\n  operation             list, view, fetch, verify, create, latest or delete\n  target                tag and path to release artifacts directory\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to release identity\n  -s PATH, --signer PATH\n                        path to signing identity, if different from release\n                        identity\n  -n name, --name name  package name if different from repo name\n  -L, --local           generate release locally, but don't upload\n  -o, --offline         verify manifest locally, but don't fetch updates\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
    Run(
      name: "permissions help",
      arguments: ["perms", "--help"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH] [-v]\n             [-q] [--version]\n             remote\n\nReticulum Git Release Manager\n\npositional arguments:\n  remote                URL of remote group or repository\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to release identity\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
    Run(
      name: "work help",
      arguments: ["work", "--help"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH]\n             [--scope SCOPE] [-t TITLE] [-d ID] [-v] [-q] [--version]\n             [repository] [operation]\n\nReticulum Git Work Document Manager\n\npositional arguments:\n  repository            URL of remote repository\n  operation             list, view, create, propose, edit, delete, update,\n                        complete, activate or perms\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to identity\n  --scope SCOPE         document scope: active, completed or all\n  -t TITLE, --title TITLE\n                        document title for create\n  -d ID, --id ID        document ID\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
    Run(
      name: "fork help",
      arguments: ["fork", "--help"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH] [-v]\n             [-q] [--version]\n             source target\n\nReticulum Git Repository Forker\n\npositional arguments:\n  source                URL of source repository\n  target                URL of target repository\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to identity\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
    Run(
      name: "sync help",
      arguments: ["sync", "--help"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH] [-v]\n             [-q] [--version]\n             repository\n\nReticulum Git Repository Syncer\n\npositional arguments:\n  repository            URL of repository\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to identity\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
    Run(
      name: "mirror help",
      arguments: ["mirror", "--help"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-i PATH]\n             [--scope SCOPE] [-v] [-q] [--version]\n             source target\n\nReticulum Git Mirror Management\n\npositional arguments:\n  source                URL of source repository\n  target                URL of target repository\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -i PATH, --identity PATH\n                        path to identity\n  --scope SCOPE         document scope: active, completed or all\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
    Run(
      name: "help with no subcommand",
      arguments: ["--help"],
      standardOutput:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-p] [-s] [-i]\n             [-v] [-q] [--version]\n\nReticulum Git Repository Node\n\noptions:\n  -h, --help            show this help message and exit\n  --config CONFIG       path to alternative config directory\n  --rnsconfig RNSCONFIG\n                        path to alternative Reticulum config directory\n  -p, --print-identity  print identity and destination info and exit\n  -s, --service         rngit is running as a service and should log to file\n  -i, --interactive     drop into interactive shell after initialisation\n  -v, --verbose\n  -q, --quiet\n  --version             show program's version number and exit\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
    Run(
      name: "an option that is not declared",
      arguments: ["node", "--nonesuch"],
      standardOutput: "",
      standardError:
        "usage: rngit [-h] [--config CONFIG] [--rnsconfig RNSCONFIG] [-p] [-s] [-i]\n             [-v] [-q] [--version]\nrngit: error: unrecognized arguments: --nonesuch\n",
      exitCode: 2,
      setup: nil),
    Run(
      name: "the version",
      arguments: ["--version"],
      standardOutput: "rngit 0.0.0\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
    Run(
      name: "the version under a subcommand",
      arguments: ["create", "--version"],
      standardOutput: "rngit 0.0.0\n",
      standardError: "",
      exitCode: 0,
      setup: nil),
  ]

  /// Every `git-remote-rns` command line recorded from the reference.
  private static let readings: [Reading] = [
    Reading(
      name: "a remote and a URL",
      arguments: ["origin", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      environment: [:],
      standardError: "",
      exitCode: nil,
      configDirectory: nil,
      rnsConfigDirectory: nil,
      destination: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      group: "group",
      repository: "repo"),
    Reading(
      name: "a repository name carrying a slash",
      arguments: ["origin", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/g/r/deep"],
      environment: [:],
      standardError: "",
      exitCode: nil,
      configDirectory: nil,
      rnsConfigDirectory: nil,
      destination: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      group: "g",
      repository: "r/deep"),
    Reading(
      name: "no arguments",
      arguments: [],
      environment: [:],
      standardError: "Usage: git-remote-rns <remote-name> <url>\n",
      exitCode: 1,
      configDirectory: nil,
      rnsConfigDirectory: nil,
      destination: nil,
      group: nil,
      repository: nil),
    Reading(
      name: "only a remote",
      arguments: ["origin"],
      environment: [:],
      standardError: "Usage: git-remote-rns <remote-name> <url>\n",
      exitCode: 1,
      configDirectory: nil,
      rnsConfigDirectory: nil,
      destination: nil,
      group: nil,
      repository: nil),
    Reading(
      name: "three arguments",
      arguments: ["origin", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo", "extra"],
      environment: [:],
      standardError: "",
      exitCode: nil,
      configDirectory: nil,
      rnsConfigDirectory: nil,
      destination: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      group: "group",
      repository: "repo"),
    Reading(
      name: "a URL under another scheme",
      arguments: ["origin", "https://example.org/g/r"],
      environment: [:],
      standardError: "Invalid URL scheme. Must be rns://\n",
      exitCode: 1,
      configDirectory: nil,
      rnsConfigDirectory: nil,
      destination: nil,
      group: nil,
      repository: nil),
    Reading(
      name: "a URL naming no repository",
      arguments: ["origin", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/g"],
      environment: [:],
      standardError: "Invalid URL format. Use rns://<hash>/<group>/<repo>\n",
      exitCode: 1,
      configDirectory: nil,
      rnsConfigDirectory: nil,
      destination: nil,
      group: nil,
      repository: nil),
    Reading(
      name: "a URL naming only a destination",
      arguments: ["origin", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"],
      environment: [:],
      standardError: "Invalid URL format. Use rns://<hash>/<group>/<repo>\n",
      exitCode: 1,
      configDirectory: nil,
      rnsConfigDirectory: nil,
      destination: nil,
      group: nil,
      repository: nil),
    Reading(
      name: "a URL naming nothing at all",
      arguments: ["origin", "rns://"],
      environment: [:],
      standardError: "Invalid URL format. Use rns://<hash>/<group>/<repo>\n",
      exitCode: 1,
      configDirectory: nil,
      rnsConfigDirectory: nil,
      destination: nil,
      group: nil,
      repository: nil),
    Reading(
      name: "a URL whose destination is an alias",
      arguments: ["origin", "rns://mynode/g/r"],
      environment: [:],
      standardError: "",
      exitCode: nil,
      configDirectory: nil,
      rnsConfigDirectory: nil,
      destination: "mynode",
      group: "g",
      repository: "r"),
    Reading(
      name: "a configuration directory from the environment",
      arguments: ["origin", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      environment: ["RNGIT_CONFIG": "/tmp/rngit"],
      standardError: "",
      exitCode: nil,
      configDirectory: "/tmp/rngit",
      rnsConfigDirectory: nil,
      destination: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      group: "group",
      repository: "repo"),
    Reading(
      name: "a reticulum configuration directory from the environment",
      arguments: ["origin", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      environment: ["RNS_CONFIG": "/tmp/reticulum"],
      standardError: "",
      exitCode: nil,
      configDirectory: nil,
      rnsConfigDirectory: "/tmp/reticulum",
      destination: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      group: "group",
      repository: "repo"),
    Reading(
      name: "both directories from the environment",
      arguments: ["origin", "rns://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/group/repo"],
      environment: ["RNGIT_CONFIG": "/tmp/rngit", "RNS_CONFIG": "/tmp/reticulum"],
      standardError: "",
      exitCode: nil,
      configDirectory: "/tmp/rngit",
      rnsConfigDirectory: "/tmp/reticulum",
      destination: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      group: "group",
      repository: "repo"),
  ]

  /// The version the run prints, which stands where the reference printed its own.
  private static let version = "0.0.0"

  func testEveryCommandLineMatchesTheReference() throws {
    for run in Self.runs {
      let read = RNGitCommandLine.reading(run.arguments, version: Self.version)
      XCTAssertEqual(read.standardOutput, run.standardOutput, run.name)
      XCTAssertEqual(read.standardError, run.standardError, run.name)
      XCTAssertEqual(read.exitCode, run.exitCode, run.name)

      guard let expected = run.setup else {
        XCTAssertNil(read.setup, run.name)
        continue
      }
      guard let setup = read.setup else {
        XCTFail("no setup for " + run.name)
        continue
      }
      XCTAssertEqual(setup.configDirectory, expected.configDirectory, run.name)
      XCTAssertEqual(setup.rnsConfigDirectory, expected.rnsConfigDirectory, run.name)
      XCTAssertEqual(setup.verbosity, expected.verbosity, run.name)
      XCTAssertEqual(setup.quietness, expected.quietness, run.name)
      XCTAssertEqual(setup.service, expected.service, run.name)
      XCTAssertEqual(setup.interactive, expected.interactive, run.name)
      XCTAssertEqual(setup.printIdentity, expected.printIdentity, run.name)
      XCTAssertEqual(setup.identity, expected.identity, run.name)
      XCTAssertEqual(setup.signer, expected.signer, run.name)

      guard let wanted = expected.task else {
        XCTAssertNil(setup.task, run.name)
        continue
      }
      guard let task = setup.task else {
        XCTFail("no task for " + run.name)
        continue
      }
      XCTAssertEqual(task.command.rawValue, wanted.command, run.name)
      XCTAssertEqual(task.operation, wanted.operation, run.name)
      XCTAssertEqual(task.remote, wanted.remote, run.name)
      XCTAssertEqual(task.source, wanted.source, run.name)
      XCTAssertEqual(task.target, wanted.target, run.name)
      XCTAssertEqual(task.signer, wanted.signer, run.name)
      XCTAssertEqual(task.name, wanted.name, run.name)
      XCTAssertEqual(task.noUpload, wanted.noUpload, run.name)
      XCTAssertEqual(task.offline, wanted.offline, run.name)
      XCTAssertEqual(task.scope, wanted.scope, run.name)
      XCTAssertEqual(task.documentIdentifier, wanted.documentIdentifier, run.name)
      XCTAssertEqual(task.title, wanted.title, run.name)
    }
  }

  func testEveryHelperCommandLineMatchesTheReference() throws {
    for reading in Self.readings {
      let read = RNGitHelperCommandLine.reading(
        reading.arguments, environment: reading.environment)
      XCTAssertEqual(read.standardError, reading.standardError, reading.name)
      XCTAssertEqual(read.exitCode, reading.exitCode, reading.name)
      XCTAssertEqual(read.setup?.configDirectory, reading.configDirectory, reading.name)
      XCTAssertEqual(read.setup?.rnsConfigDirectory, reading.rnsConfigDirectory, reading.name)
      XCTAssertEqual(read.setup?.url.destination, reading.destination, reading.name)
      XCTAssertEqual(read.setup?.url.group, reading.group, reading.name)
      XCTAssertEqual(read.setup?.url.repository, reading.repository, reading.name)
    }
  }
}
